import datetime
import pytest

from SRC.model.errores_actividad import ErrorDescripcion,ErrorFechaHora,ErrorFechaHoraInvalida, ErrorFechaInvalida, ErrorNoFechas, ErrorSesionNoIniciada
from SRC.model.errores_usuario import ErrorNoEmail,ErrorEmailNo,ErrorEmailYa,ErrorContraseñaCorta,ErrorContraseñaIncorrecta,ErrorContraseñaAnteriorIn,ErrorContraseñaNoCoincide
from SRC.model.actividad import Actividad,Archivo
from SRC.model.supervisor import Supervisor

